name: 'Delete workflow artifacts for branch'
description: 'Delete all artifacts from a given workflow'
author: 'Donovan Fournier'
inputs:
  workflow-id:
    required: true
    description: 'The ID of the workflow from which we need to delete the artifacts'
  github-token:
    required: true
    description: 'Github token'
  branch-name:
    description: 'The branch name'
    required: false
    default: ${{ github.head_ref }}
runs:
  using: 'node16'
  main: 'dist/index.js'
